"""empty message

Revision ID: 063938613373
Revises: 
Create Date: 2017-04-30 18:26:16.527063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063938613373'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=130), nullable=True),
    sa.Column('image', sa.String(length=30), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('profile_added_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('wishlist',
    sa.Column('itemid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('thumbnailurl', sa.String(length=500), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['profiles.userid'], ),
    sa.PrimaryKeyConstraint('itemid')
    )
    op.create_table('users_wishes',
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('wishid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['profiles.userid'], ),
    sa.ForeignKeyConstraint(['wishid'], ['wishlist.itemid'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_wishes')
    op.drop_table('wishlist')
    op.drop_table('profiles')
    # ### end Alembic commands ###
